#-------------------------------
# General Site Settings
title: Artificial Intelligence Digital Twin Lab
logo: Logo_Wide.png
#LabLogo.png
description: Official website of the AI Digital Twin at Dong-A University of Korea (AIDT Lab@DAU)
author: AIDT Lab@DAU
creator: AIDT Lab@DAU
publisher: AIDT Lab@DAU

#-------------------------------
# Author Settings
author:
  name: AIDT Lab@DAU
  image: 220908_2.jpg
  #logo_please.png
  say-hello: <strong>Artificial Intelligence Digital Twin Lab</strong>
  bio: The AI DT Lab at Dong A University focuses on advancing research in artificial intelligence, particularly in areas such as data analysis, machine learning, and computer vision. It aims to foster innovation and collaboration among students and researchers to solve real-world problems using AI technologies.


#-------------------------------
# Contact links
twitter: 
#facebook: https://facebook.com/ # Add your Facebook handle
#dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram:  # Add your Instagram handle
#pinterest: https://pinterest.com/ # Add your Pinterest handle
github: https://github.com/AIDTLab-DAU
email: mailto
demopage: 
youtube: 


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: # Add instagram username


#-------------------------------
# Google Analytics
google-analytics: G-3WYKVC20DN # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
